name: Python-App-Pipeline-Example

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            pip install -r requirments_dev.txt

        - name: Lint with ruff
          run: |
            ruff check .

        - name: Test with pytest
          run: |
            
    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Login to Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: orfav/python-pipeline-example:${{github.sha}}